CREATE TABLE car
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    color     VARCHAR(255)                            NOT NULL,
    engine_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_car PRIMARY KEY (id)
);

CREATE TABLE car_equipment_options
(
    car_id               BIGINT NOT NULL,
    equipment_options_id BIGINT NOT NULL
);

CREATE TABLE engine
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    horse_power INTEGER                                 NOT NULL,
    CONSTRAINT pk_engine PRIMARY KEY (id)
);

CREATE TABLE equipment_option
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_equipmentoption PRIMARY KEY (id)
);

ALTER TABLE car
    ADD CONSTRAINT uc_car_name UNIQUE (name);

ALTER TABLE engine
    ADD CONSTRAINT uc_engine_name UNIQUE (name);

ALTER TABLE equipment_option
    ADD CONSTRAINT uc_equipmentoption_name UNIQUE (name);

ALTER TABLE car
    ADD CONSTRAINT FK_CAR_ON_ENGINE FOREIGN KEY (engine_id) REFERENCES engine (id);

ALTER TABLE car_equipment_options
    ADD CONSTRAINT fk_carequopt_on_car FOREIGN KEY (car_id) REFERENCES car (id);

ALTER TABLE car_equipment_options
    ADD CONSTRAINT fk_carequopt_on_equipment_option FOREIGN KEY (equipment_options_id) REFERENCES equipment_option (id);
