api:
  baseUrl: http://localhost:8080/api
  endpoints:
    cars: /cars
    engines: /engines
    equipmentOptions: /equipment-options
server:
  port: 80
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
